apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
spec:
  replicas: 1 # Adjust replica count as needed
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        ports:
        - containerPort: 8096
        volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /cache
          name: cache-volume
        - mountPath: /movies
          name: media-volume
      volumes:
      - name: config-volume
        hostPath: 
          path: /media/jellyfin/config
          type: DirectoryOrCreate
      - name: cache-volume
        hostPath:
          path: /media/jellyfin/cache
          type: DirectoryOrCreate
      - name: media-volume
        nfs:
          server: kind-server
          path: /media/movies
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: NodePort
  selector:
    app: jellyfin
  ports:
  - port: 8096
    targetPort: 8096
    nodePort: 30000
