---
- name: Setup Fedora
  hosts: localhost

  tasks:
    - name: Vim
      become: true
      dnf:
        update_cache: yes
      dnf:
        name: vim
        state: present

    - name: Snap
      become: true
      dnf:
        update_cache: yes
      dnf:
        name: snapd
        state: present

    - name: Check if file exists
      stat:
        path: /snap/snap
      register: file_stat

    - name: Make snap program accessible
      become: true
      shell: ln -s /var/lib/snapd/snap /snap
      when: not file_stat.stat.exists

    - name: Cheat
      become: true
      snap:
        name: cheat
        state: present

    - name: Check cheatsheets dir exists
      stat:
        path: ~/snap/cheat/common/.config/cheat/cheatsheets
      register: cheatsheets_stat

    - name: Cheat cheatsheets dir
      become: true
      command: mkdir ~/snap/cheat/common/ ~/snap/cheat/common/.config/ ~/snap/cheat/common/.config/cheat/ ~/snap/cheat/common/.config/cheat/cheatsheets
      when: not cheatsheets_stat.stat.exists

    - name: Check personal cheatsheets dir exists
      stat:
        path: ~/snap/cheat/common/.config/cheat/cheatsheets/personal
      register: cheatsheets_personal_stat

    - name: Cheat clone personal repo
      command: git clone https://github.com/Anton-Augustsson/.cheat.git ~/snap/cheat/common/.config/cheat/cheatsheets/personal/
      when: not cheatsheets_personal_stat.stat.exists

    - name: AATTS
      shell: echo "TODO cheat" 

    - name: Rclone
      shell: echo "TODO rclone" 

    - name: Install vscode
      shell: echo "TODO vscode" 

    - name: Install vscode extesnion
      debug:
        msg: "TODO vscode extesnion"

    - name: Zoom
      debug:
        msg: "TODO zoom test"

    - name: Config
      shell: echo "TODO config" 
