---
- name: Setup Fedora
  hosts: localhost

  tasks:
    - name: Snap
      block:
        - name: Install snap
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: snapd
            state: present
        - name: Check if snap file exists
          stat:
          path: /snap/snap
          register: file_stat
        - name: Make snap program accessible
          become: true
          shell: ln -s /var/lib/snapd/snap /snap
          when: not file_stat.stat.exists
    - name: Cheat
      block:
        - name: Install cheat
          become: true
          snap:
            name: cheat
            state: present
        - name: Check if snap dir exists
          stat:
            path: ~/snap/
          register: snap_stat
        - name: Create snap dir 
          command: mkdir ~/snap
          when: not snap_stat.stat.exists
        - name: Check if cheat dir exists
          stat:
            path: ~/snap/cheat/
          register: cheat_stat
        - name: Create Cheat dir
          command: mkdir ~/snap/cheat
          when: not cheat_stat.stat.exists
        - name: Check if cheat common dir exists
          stat:
            path: ~/snap/cheat/common
          register: common_stat
        - name: Create cheat common dir
          command: mkdir ~/snap/cheat/common/
          when: not common_stat.stat.exists
        - name: Check if cheat cheatsheets dir exists
          stat:
            path: ~/snap/cheat/common/.config/cheat/cheatsheets
          register: cheatsheets_stat
        - name: Create Cheat cheatsheets dir
          command: mkdir ~/snap/cheat/common/.config/ ~/snap/cheat/common/.config/cheat/ ~/snap/cheat/common/.config/cheat/cheatsheets ~/snap/cheat/common/.config/cheat/cheatsheets/community
          when: not cheatsheets_stat.stat.exists
        - name: Check if cheat cheatsheets config 
          stat:
            path: ~/snap/cheat/common/.config/cheat/conf.yml
          register: cheatsheets_conf_stat
        - name: Cheat cheatsheets config
          command: cp fedora/dotfiles/cheat/snap/cheat/common/.config/cheat/conf.yml ~/snap/cheat/common/.config/cheat/conf.yml
          when: not cheatsheets_conf_stat.stat.exists
        - name: Check if personal cheatsheets dir exists
          stat:
            path: ~/snap/cheat/common/.config/cheat/cheatsheets/personal
          register: cheatsheets_personal_stat
        - name: Cheat clone personal repo
          command: git clone https://github.com/Anton-Augustsson/.cheat.git ~/snap/cheat/common/.config/cheat/cheatsheets/personal/
          when: not cheatsheets_personal_stat.stat.exists
    - name: Programs
      block:
        - name: Install Vim
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: vim
            state: present
        - name: Make programs dir
          command: mkdir -p ~/Programs
        - name: Clone AATTS repo
          command: git clone git@github.com:Anton-Augustsson/tts.git ~/Programs/tts
        - name: Install AATTS
          command: (cd ~/Programs/tts && make install)
        - name: Install vscode
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: code
            state: present
        - name: Install Zoom
          snap:
            name: zoom-client
            state: present
        - name: Install KiCad
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: kicad
            state: present
        - name: Install OpenScad
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: openscad
            state: present

        - name: Install Gimp
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: gimp
            state: present
    - name: Zsh
      block:
        - name: Install zsh
          shell: echo "TODO zsh" 
    - name: config
      block:
        - name: Install stow
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: stow
            state: present
        - name: Configure zsh
          command: (cd dotfiles && zsh)
    - name: Google Drive
      block:
        - name: Install Rclone
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: rclone
            state: present
        - name: Configure Rclone
          shell: echo "RUN rclone configure" 
        - name: Copy google drive folder
          shell: echo "RUN rclone copy <source> ~/Documents/<destination folder>"
    - name: PiDrive
      block:
        - name: Install sshfs
          become: true
          dnf:
            update_cache: yes
          dnf:
            name: fuse-sshfs
            state: present
        - name: Mount PiDrive
          shell: echo "RUN sshfs <source> ~/Documents/Pidrive install sshfs and create folder" 

