---
- name: Setup Fedora
  hosts: localhost

  tasks:
    - name: Vim
      become: true
      dnf:
        update_cache: yes
      dnf:
        name: vim
        state: present

    - name: Snap
      become: true
      dnf:
        update_cache: yes
      dnf:
        name: snapd
        state: present

    - name: Check if file exists
      stat:
        path: /snap/snap
      register: file_stat

    - name: Make snap program accessible
      become: true
      shell: ln -s /var/lib/snapd/snap /snap
      when: not file_stat.stat.exists

    - name: Cheat
      become: true
      snap:
        name: cheat
        state: present

    - name: Check snap dir exists
      stat:
        path: ~/snap/
      register: snap_stat

    - name: Create snap dir 
      command: mkdir ~/snap
      when: not snap_stat.stat.exists

    - name: Check cheat dir exists
      stat:
        path: ~/snap/cheat/
      register: cheat_stat

    - name: Create Cheat dir
      command: mkdir ~/snap/cheat
      when: not cheat_stat.stat.exists

    - name: Check cheat common dir exists
      stat:
        path: ~/snap/cheat/common
      register: common_stat

    - name: Create cheat common dir
      command: mkdir ~/snap/cheat/common/
      when: not common_stat.stat.exists

    - name: Check cheat cheatsheets dir exists
      stat:
        path: ~/snap/cheat/common/.config/cheat/cheatsheets
      register: cheatsheets_stat

    - name: Create Cheat cheatsheets dir
      command: mkdir ~/snap/cheat/common/.config/ ~/snap/cheat/common/.config/cheat/ ~/snap/cheat/common/.config/cheat/cheatsheets ~/snap/cheat/common/.config/cheat/cheatsheets/community
      when: not cheatsheets_stat.stat.exists

    - name: Check cheat cheatsheets config 
      stat:
        path: ~/snap/cheat/common/.config/cheat/conf.yml
      register: cheatsheets_conf_stat

    - name: Cheat cheatsheets config
      command: cp fedora/dotfiles/cheat/snap/cheat/common/.config/cheat/conf.yml ~/snap/cheat/common/.config/cheat/conf.yml
      when: not cheatsheets_conf_stat.stat.exists

    - name: Check personal cheatsheets dir exists
      stat:
        path: ~/snap/cheat/common/.config/cheat/cheatsheets/personal
      register: cheatsheets_personal_stat

    - name: Cheat clone personal repo
      command: git clone https://github.com/Anton-Augustsson/.cheat.git ~/snap/cheat/common/.config/cheat/cheatsheets/personal/
      when: not cheatsheets_personal_stat.stat.exists

    - name: AATTS
      shell: echo "TODO cheat" 

    - name: Rclone
      shell: echo "TODO rclone" 

    - name: Install vscode
      shell: echo "TODO vscode" 

    - name: Install vscode extesnion
      debug:
        msg: "TODO vscode extesnion"

    - name: Zoom
      debug:
        msg: "TODO zoom test"

    - name: Config
      shell: echo "TODO config" 
