---
- name: Setup Fedora
  hosts: localhost

  tasks:
    - name: Vim
      become: true
      dnf:
        update_cache: yes
      dnf:
        name: vim
        state: present

    - name: Snap
      become: true
      dnf:
        update_cache: yes
      dnf:
        name: snapd
        state: present

    - name: Make snap program accessible
      become: true
      command: ln -s /var/lib/snapd/snap /snap

    - name: Cheat
      become: true
      snap:
        name: cheat
        state: present

    - name: Cheat personal repo
      command: mkdir cheatsheets/personal

    - name: AATTS
      shell: echo "TODO cheat" 

    - name: Rclone
      shell: echo "TODO rclone" 

    - name: Install vscode
      shell: echo "TODO vscode" 

    - name: Install vscode extesnion
      debug:
        msg: "TODO vscode extesnion"

    - name: Zoom
      debug:
        msg: "TODO zoom test"

    - name: Config
      shell: echo "TODO config" 
